describe('supplier page', () => {
  beforeEach(() => {
    cy.login()
    cy.visit('/suppliers')
  })

  it('supplier page loads', () => {
    cy.contains('Manual')
    cy.contains('The Grocery Store')
    cy.contains('Neighbor')
    cy.contains('Baker')
    cy.contains('New Supplier')
  })

  it('edits suppliers', () => {
    cy.contains('Baker')
      .click()
      .get('[name="supplierName"]')
      .type('12345678')
      .get('[name="deliveryDay"]')
      .select('Tuesday')
      .get('[name="salesPersonName"]')
      .type('mark')
      .get('[name="salesPersonPhoneNumber"]')
      .type('9841316')
      .get('[name="salesPersonEmail"]')
      .type('mark@mark.com')
      .get('[name="officePhoneNumber"]')
      .type('91131683')
    cy.contains('Save').click()
    cy.contains('Cancel').click()
    cy.contains('Baker12345678')
      .parent()
      .should('contain', '91131683')
      .and('contain', 'Tuesday')
      .and('contain', 'mark')
      .and('contain', '9841316')
      .and('contain', 'mark@mark.com')
  })
  it('does not delete used suppliers', () => {
    cy.contains('Neighbor').click()
    cy.contains('Delete').click()
    cy.contains('The most current order is using this supplier.')
  })
  it('creates new supplier', () => {
    cy.contains('New Supplier')
      .click()
      .get('[name="supplierName"]')
      .type("Chuck's 22")
    cy.contains('Save').click()
    cy.contains("Chuck's 22").parent().should('contain', 'office phone')
  })
  it('deletes suppliers', () => {
    cy.contains("Chuck's 22").click()
    cy.contains('Delete').click()
    cy.contains("Chuck's 22").should('not.exist')
  })
})
